export enum HTTP_METHOD {
  GET = "GET",
  POST = "POST",
  PUT = "PUT",
  DELETE = "DELETE",
}

export enum ROLE {
  PARENT = "Parent",
  CHILD = "Child",
}

export enum CHORE_STATUS {
  COMPLETED = "COMPLETED",
  APPROVAL = "AWAITING_APPROVAL",
  NOT_ACCEPTED = "NOT_ACCEPTED",
  IN_PROGRESS = "IN_PROGRESS",
}

export enum TRANSACTION_STATUS {
  DEPOSIT = "DEPOSIT",
  WITHDRAWAL = "WITHDRAWAL",
  PENDING = "PENDING",
  DENIED = "DENIED",
}
